drop table if exists bookmarks;

create table bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT NOT NULL,
    rating INTEGER NOT NULL
);

insert into bookmarks (title, url, description, rating)
VALUES
    ('Google', 'https://www.google.com', 'It is big search time', 5),
    ('Youtube', 'https://www.youtube.com', 'Where you can find funny videos and Donald Trump', 1);